### ISSUE TITLE
AttributeError: module 'ST7735' has no attribute 'BG_SPI_CSB_BACK'

### ISSUE THREAD

**Issue by s51517765** [pimoroni/st7735-python#21]
I have Installed and tried.
$sudo python3 scrolling-text.py
or Other scripts. 
I have bellow error.

>>>
Traceback (most recent call last):
  File "scrolling-text.py", line 14, in <module>
    cs=ST7735.BG_SPI_CSB_BACK,  # BG_SPI_CSB_BACK or BG_SPI_CS_FRONT
AttributeError: module 'ST7735' has no attribute 'BG_SPI_CSB_BACK'
>>>

BG_SPI_CSB_BACK and BG_SPI_CS_FRONT have the same result.
Please help me.

No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Python 3.7.3

**Comment by s51517765** [comment]
I have resolved myself, sorry.
BG_SPI_CSB_BACK in comment is miss type.
Correctly is BG_SPI_CS_BACK.

I think you should get a pull request.
Should I put it out?

**Comment by Gadgetoid** [comment]
I think I fixed these as part of https://github.com/pimoroni/st7735-python/commit/ed2b0af910a190e679ddab1ea8605702ba9b2fdb

Thank you!
