### ISSUE TITLE
Incorrect colors when using Raspberry Pi 4 (Bullseye) and Adafruit ST7735R display.

### ISSUE THREAD

**Issue by lynniemagoo** [pimoroni/st7735-python#22]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  Raspberry Pi Bullseye 

- Python version (run `python -version` or `python3 -version`): Python 3.9.2

- Error message you are receiving, including any Python exception traces:  No Error Messages

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): Run attached imagePortrait.py against attached file parrot.bmp

Compare the results to parrot.bmp as displayed in Chrome on Windows or any other system.

I'm using the Adafruit ST7735R 160 x 128 display with the Green tab on the screen protector.

Note that if you are using the stock example image.py you will also see that cat.jpg is not displayed with correct colors on the display.

I'm going to do a PR which will fix the issue but I don't have a Pimoroni display with which to test against.

[Adafruit7735RIncorrectColors.zip](https://github.com/pimoroni/st7735-python/files/8275431/Adafruit7735RIncorrectColors.zip)

**Comment by Gadgetoid** [comment]
These displays have a colour order bit in the MADCTL register (0x36) which can be set, instead of changing the output data format code; which would break the colour order on the displays this was originally written to support.

See: https://cdn-shop.adafruit.com/datasheets/ST7735R_V0.2.pdf

It's sent to the LCD here: https://github.com/pimoroni/st7735-python/blob/1a70d3ae7eee6f376de430c944ff4e95d294543e/library/ST7735/__init__.py#L287-L288

The library init would need a new property like `bgr` which accepts `True` or `False` and sets this bit accordingly.

To test in your case, you can revert your changes and try setting the RGB bit:

```python
        self.command(ST7735_MADCTL)     # Memory access control (directions)
        self.data(0xC8 | 0b00001000)                 # row addr/col addr, bottom to top refresh
```

**Comment by lynniemagoo** [comment]
OK.  Had some time to review your comment and the PDF again.

Apologies if we are holding a discussion here.  

0xC8 === 0b11001000 

And asking to OR a value of 8 with this value yields 0xC8 or 0b11001000..

Isn't this a NO-OP?

I understand the and agree with the concern for breaking original displays.  

The question I have is if you have the display available, when you run the example image.py with invert=True, does it properly display the cat.jpg on the intended display? Or does it perhaps reverse the red and blue pixels?

I'm hoping the answer is yes and if that is the case, maybe does this because _init_ defaults to a value of invert=true?

Based on the way the code is currently written, sets a MADCTL value of 0xC8 which sets value of 1 for bit D3 which is telling the display to use BGR format and not RGB format which is the pixel format that the JPEG gets converted to by PIL.

A value of 1 in Bit D3 is what you currently have as the default.  Instead I will rework this PR with a value of

**Comment by lynniemagoo** [comment]
Just completed all testing of PR and can confirm that all examples function as expected on Adafruit 358 using invert=False, bgr=False.

Hope you will accept this PR and provide a version 0.0.5 so I don't have to use my local edits.

**Comment by lynniemagoo** [comment]
I just reviewed the adafruit cpp implementation and it also sets MADCTL to 0xC8.  So it appears that all the implementations thus far specify bgr.  Therefore I am now of the opinion that the current implementation with the bgr color ordering is best as it is coupled with both MADCTL value as well as the endianess of the platform. 

If this library could support this new bgr init param, I think we have the best of all worlds.  At some point, I would to port this code along with the adafruit cpp library to a combined NodeJS implementation similar to the one currently available for the SSD1351 Oled display. I will cite both this lib as well as adafruit when I do so.

**Comment by Gadgetoid** [comment]
Sorry, it looks like we're a timezone or two apart here!

Anyway your sleuthing seems correct. I had mistakenly thought that we'd *not* be setting BGR and didn't think to unpack  `0xC8`1 into bits before suggesting that change.

You seem to have come to the right conclusion, anyway, and the PR looks good! Thank you.

**Comment by lynniemagoo** [comment]
I'm in US in CST/CDT. (Texas).

You're welcome.  I personally did not like the defaults of BGR (even in Adafruit) and then the invert=True in this library but as long as we have dials to turn for both 'bgr' and 'invert', I think it will be OK.
