### ISSUE TITLE
One (or more?) remark about the project or why we better to use the kernel module

### ISSUE THREAD

**Issue by ashevche** [pimoroni/st7735-python#27]
(Feel free to close it, it's not a bug report, rather the note to people who would like to understand why this library is needed)

The Linux kernel community is trying hard to support as much as possible popular hardware in the kernel space. The advantages are (among others):

- the kernel provides the standard ABIs that may be used by user space without creating a not invented here code (note, that Python has a comprehensive libraries to cover most of the well used ABIs, including framebuffer devices and DRI)
- the kernel driver supports much wider set of the displays (even of the same family)
- the C code is much faster than Python (in terms of device driver), because the latter still needs to go to the kernel space and do a lot of context switches
- it's being supported by the kernel community to be up-to-date
- last but not least the kernel itself has a huge test base for the code it provides

So, honestly, I do think we should encourage people to use kernel module.

**Comment by Gadgetoid** [comment]
I disagree.

If the Python hobbyist, maker and education community defer completely to Linux and already existing device drivers, how are they ever supposed to peer under the hood and see code that they could conceivably understand and learn from?

The act of writing and maintaining drivers has great educational merit, and this library - and others like it - offer the chance to do that in a language Python developers understand, using tools and processes that Python developers understand.

If someone gets to the point they need a faster driver with more tests and device support, they can probably make the determination to use a in-tree driver on their own.
