### ISSUE TITLE
To be plugged in the front slot of the breakout garden?

### ISSUE THREAD

**Issue by calocedrus** [pimoroni/st7735-python#9]
The examples `framerate.py`, `image.py` and `shapes.py` show the message "`If you're using Breakout Garden, plug the 0.96" LCD (SPI) breakout into the rear slot`" ; but it seems the LCD breakout only works (for me at least) when plugged in the front slot of the breakout garden, as stated in `gif.py`.
Or can the breakout function in either the front or rear slot?

**Comment by Gadgetoid** [comment]
See: https://github.com/pimoroni/st7735-python/blob/4f0d537021bee16839c3fe3c29dcf3441658c5aa/examples/gif.py#L42

It should work in either- but the code must be changed depending upon which slot you're using.
